import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  card: { borderRadius: 8, overflow: "hidden" },
  cardTitle: { backgroundColor: "#582a51" },
  title: { color: "#fff", fontWeight: "700" },
  subtitle: { color: "#fff" },
  avatarIcon: { backgroundColor: "#fff" },
  topheader: { borderRadius: 0, overflow: "hidden" },
  tableRow: { flexDirection: "row", alignItems: "flex-start" },
  leftBlock: { borderRightWidth: 1, borderRightColor: "#ddd" },
  rowday: { flexDirection: "row", alignItems: "center", minHeight: 80 },
  rowhead: { flexDirection: "row", alignItems: "center", minHeight: 80 },
  row: { flexDirection: "row", alignItems: "center", minHeight: 80 },
  headerRow: { backgroundColor: "#582a51" },
  cell: {
    borderRightWidth: 1,
    borderRightColor: "#ddd",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 6,
  },

  headerText: {
    color: "#fff",
    fontWeight: "700",
    textAlign: "center",
    fontSize: 16,
  },
  headerDay: {
    color: "#fff",
    fontWeight: "700",
    textAlign: "center",
    fontSize: 10,
  },
  headerMessage: {
    color: "gray",
    fontWeight: "700",
    textAlign: "center",
    fontSize: 6,
  },
  cellText: { color: "#000", textAlign: "center" },
  rowEven: { backgroundColor: "#fafafa" },
  rowOdd: { backgroundColor: "#fff" },
  iconWrapper: {
    borderWidth: 2,
    borderRadius: 6,
    width: 25,
    height: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  badge: {
    borderRadius: 12,
    height: 16,
  },
  badgeYellowText: {
    fontSize: 6,
    fontWeight: "600",
    backgroundColor: "#FFD700",
    color: "#000",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: "hidden",
  },
  badgeBlueText: {
    fontSize: 6,
    fontWeight: "600",
    backgroundColor: "#00BFFF",
    color: "#fff",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: "hidden",
  },
  badgePrimaryText: {
    fontSize: 6,
    fontWeight: "600",
    backgroundColor: "#007bff",
    color: "#fff",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: "hidden",
  },
  badgeEstado: {
    fontSize: 6,
    fontWeight: "600",
    backgroundColor: "#FFD700",
    color: "#000",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: "hidden",
  },
});